### ISSUE TITLE
Add support for using different OAuth2 clients

### ISSUE THREAD

**Issue by mjlime** [rkhwaja/fs.onedrivefs#55]
Since [OAuth2Session](https://github.com/requests/requests-oauthlib/blob/master/requests_oauthlib/oauth2_session.py) that is used in this library supports different types of [OAuth2 clients](https://oauthlib.readthedocs.io/en/latest/oauth2/clients/client.html) it would be convenient to be able to use the client that works with the type of token grant flow that is set up with the authentication against MS Graph API.

Currently the [Authorzation Code Grant](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow) is the only one supported, since the default OAuth2 client is [WebApplicationClient](https://oauthlib.readthedocs.io/en/latest/oauth2/clients/webapplicationclient.html).

We have a different setup and the refreshing of tokens doesn't seem to work due to this.

So my request is to add support for this.

**Comment by rkhwaja** [comment]
I think I see. We have to somehow allow a different choice for the client parameter of OAuth2Session from a choice of WebApplicationClient, MobileApplicationClient, LegacyApplicationClient, BackendApplicationClient. We can pass an enum to the OneDriveFS constructor which chooses (I'd rather avoid exposing the requests/oauthlib objects in the public interface).

Then in the client code, you do some different kind of authentication flow than the one done in `generate-credentials.py`
