### ISSUE TITLE
Reduce logging level from info to debug for OneDriveFS calls

### ISSUE THREAD

**Issue by mjlime** [rkhwaja/fs.onedrivefs#56]
When the log level is set to `info` the logs are filled with information from `fs.onedrivefs` that is irrelevant in most cases. The logs are too chatty/verbose and it would be really nice if it could be possible to reduce the logging level for all calls in `OneDriveFS` to `debug` instead if `info`.

**Comment by rkhwaja** [comment]
You can filter out those log messages from your application by using
``` python
logging.getLogger('fs.onedrivefs').setLevel(logging.WARNING)
```

That way applications can choose what level they're interested in from each of their dependencies. I think you can also set filters on the logger to filter out specific messages that you're not interested in.

**Comment by mjlime** [comment]
I know and that's what we are doing now, but I see this as an unnecessary and ugly solution to something that could be fixed by changing logging level in the library.
