### ISSUE TITLE
Package renamed in 1.1.2 and 1.1.3 wheels

### ISSUE THREAD

**Issue by anderssonjohan** [rkhwaja/fs.onedrivefs#64]
Upgrading to 1.1.3 makes `pkg_resources.require("anything")` raise a DistributionNotFound error.

Repro:

```
mkdir onedrivefs113
cd onedrivefs113
python -m venv venv
. venv/bin/activate
pip install fs.onedrivefs==1.1.3
python
>>> import pkg_resources
>>> pkg_resources.require("fs.onedrivefs")
```

Output:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'fs.onedrivefs' distribution was not found and is required by the application

```

Doing the same with 1.1.1:
```
>>> import pkg_resources
>>> pkg_resources.require("fs.onedrivefs")
[fs.onedrivefs 1.1.1 (venv/lib/python3.9/site-packages), requests-oauthlib 1.3.1 (venv/lib/python3.9/site-packages), requests 2.28.1 (venv/lib/python3.9/site-packages), fs 2.4.16 (venv/lib/python3.9/site-packages), requests 2.28.1 (venv/lib/python3.9/site-packages), oauthlib 3.2.2 (venv/lib/python3.9/site-packages), certifi 2022.9.24 (venv/lib/python3.9/site-packages), urllib3 1.26.12 (venv/lib/python3.9/site-packages), idna 3.4 (venv/lib/python3.9/site-packages), charset-normalizer 2.1.1 (venv/lib/python3.9/site-packages), six 1.16.0 (venv/lib/python3.9/site-packages), setuptools 60.5.0 (venv/lib/python3.9/site-packages), appdirs 1.4.4 (venv/lib/python3.9/site-packages)]
```

@rkhwaja I can't see any differences and the CI workflow does not include any `poetry build` command so it's unclear how you build these wheels to get repeatable builds. I do notice though that you have built v1.1.1 and v1.1.3 using different poetry versions and building with poetry 1.1.x instead of 1.0.x is changing some things. For example, the lock file no longer contains platform markers so if you build with `poetry build` you will be fine, but if you do a `poetry export` the platform markers etc will be gone in the requirements file. There are also some strange duplication going on in the supported python version metadata in the new wheel.

![image](https://user-images.githubusercontent.com/435885/203099612-3656c164-ad63-444a-ba6d-f68714df7982.png)

I was able to help out with the PR for the fix in 1.1.2 but here I can't help out since the build command is not contained in the CI workflow.

**Comment by anderssonjohan** [comment]
Ah, I didn't see the error until now. It was even in the screenshot I posted. You renamed the package in v1.1.2 so now it's broken when you try require it using the old name `fs.onedrivefs`.

It would be nice if you could make such changes as breaking and bump the major version or just make it explicit so downstreams can know. Some hint like this would be useful: https://stackoverflow.com/a/57110249/2447296

**Comment by anderssonjohan** [comment]
Ok, @rkhwaja, now I know what happened. Since you obviously changed to build the wheel using poetry-core 1.3.2, you got hit by this one: https://github.com/python-poetry/poetry/issues/6590

**Comment by anderssonjohan** [comment]
This issue can also be seen by the redirect when you try to access the package URL on pypi: https://pypi.org/simple/fs.onedrivefs/ (redirects to https://pypi.org/simple/fs_onedrivefs/)

**Comment by rkhwaja** [comment]
I uploaded a new version (1.1.4) built with poetry 1.1.15 which looks good.

The bug in the generation of the wheel and sdist is still there in the latest source code of poetry. Not sure about the publish functionality.

**Comment by anderssonjohan** [comment]
1.1.4 looks good to me!
