### ISSUE TITLE
Dependencies are no longer installed with version `1.2.0`

### ISSUE THREAD

**Issue by mjlime** [rkhwaja/fs.onedrivefs#80]
It doesn't seem like the new version (`1.2.0`) can be installed correctly with poetry, not sure why but I can see there has been [some changes to the `pyproject.toml` file](https://github.com/rkhwaja/fs.onedrivefs/commit/1db3976c3fd5090ccf22bb22a521d5adf00e7fdb) and I guess that's what's causing this problem.

The issue is that the dependencies are no longer installed.

This is the result from installing the previous version (1.1.5) and 1.2.0:

```pwsh
$ poetry add fs.onedrivefs@<1.2.0

Updating dependencies
Resolving dependencies...

Writing lock file

Package operations: 2 installs, 1 update, 0 removals

  • Installing oauthlib (3.2.2)
  • Installing requests-oauthlib (2.0.0)
  • Updating fs-onedrivefs (1.2.0 -> 1.1.5)

$ poetry add fs.onedrivefs@1.2.0

Updating dependencies
Resolving dependencies...

Writing lock file

Package operations: 0 installs, 1 update, 2 removals

  • Removing oauthlib (3.2.2)
  • Removing requests-oauthlib (2.0.0)
  • Updating fs-onedrivefs (1.1.5 -> 1.2.0)

```

**Comment by rkhwaja** [comment]
I just tried this and it didn't do the same thing as yours. It didn't add or remove any dependencies and just upgraded fs.onedrivefs.

**Comment by mjlime** [comment]
We've tried a few different scenarios and it seems very inconsistent at the moment. Our current conclusion is that it seems to be an issue on Windows with poetry 1.3.2 and defining our own pypi server in the pyproject.toml. I'll get back with more info later on when I have more information to see if it's actually an issue in this package or just local problems on our side. Sorry for reporting it before confirming it more.

Thank you for the quick response.
